"""Render a run's execution DAG as a flat, hand-written-quality Airflow ``dag_<run_id>.py``.

The Composer/Airflow counterpart to `main.run`: given a config, `emit_airflow_dag` resolves the same
DAG (`dag.plan_dag`) and prints a standalone Python file whose tasks call the callables in
`airflow_tasks` — one obvious ``PythonOperator`` per node, explicit ``>>`` edges, top-of-file
constants. The emitted file runs the *identical* run building blocks `main.run` uses (no forked
logic), so the same config produces the same run on Composer as locally, under one shared
``run_id``.

The rendered topology mirrors a live run exactly:

* ``begin_run`` writes the header; each **family** runs on its resolved runtime as its own task
  (Spark serverless / Spark cluster / Ray / BigQuery-native — chosen per family, not per run); the
  **ensemble** runs ``barrier`` (downstream of every family) or ``microbatch`` (in parallel, gated
  only on ``begin_run``); ``finalize_run`` is the terminal join.
* When a run has **several ephemeral Ray (or Dataproc-cluster) families**, a
  ``create_*_cluster`` → families → ``delete_*_cluster`` bracket is emitted (from the same
  `shared_clusters` predicates the orchestrator uses), so those
  families share one cluster. **Serverless Spark families never share** — each is its own batch
  task.

Every task is a ``PythonOperator`` (uniform operator model): each family task self-owns its
``run_jobs`` row, so the per-job trace and a concurrent microbatch ensemble both work with no
special-casing. Native Airflow Dataproc operators (`DataprocCreateBatchOperator`, the cluster
operators) are a deliberate *non*-choice here — see the module note below on when to prefer them.

The renderer is pure: it takes a config + the config's ``gs://`` (or local) URI and returns the file
source as a string, touching no GCP — so it is fully offline-testable (parse/compile the output; no
Airflow install needed to verify it). `staging.stage_dag` uploads the rendered file next to the
staged config; `main` exposes it as ``--emit-airflow``.

Alternatives, and when to prefer them (this emitter renders the uniform-PythonOperator model):

* **Hybrid native Dataproc operators + per-family finalize.** Render Spark-serverless families as
  deferrable ``DataprocCreateBatchOperator`` (and cluster families as the Dataproc cluster
  operators), pairing each with a small finalize task so its ``run_jobs`` row still flips in real
  time. Prefer this when a Composer environment runs **many** of these DAGs concurrently and the
  worker slots a blocking ``PythonOperator`` holds during a multi-hour Spark batch become the
  bottleneck — deferrable operators free the slot while the batch runs. Cost: ~2-3x the tasks.
* **Hybrid native operators + a single reconcile-at-finalize.** Same native operators, but one
  terminal task reconciles all ``run_jobs`` rows at the end. The fewest tasks, but the rows stay
  RUNNING until the end, so a **microbatch** ensemble cannot use the registry as its stop-signal —
  prefer only for **barrier-only** deployments where DAG concurrency is high.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from .config import RunConfig
    from .dag import RunDag


def _str(value: str) -> str:
    """A double-quoted Python string literal for the emitted source (properly escaped).

    ``json.dumps`` gives a stable, always-double-quoted literal — so the generated file reads with
    one consistent quote style rather than the mixed quotes ``repr`` would produce.
    """
    return json.dumps(value)


# The file preamble: the auto-generated banner + imports + a single ``DAG(...)`` context. A fixed
# ``start_date`` (not a wall-clock call) keeps the emitted file deterministic — the same config
# always renders byte-identical source.
_PREAMBLE = '''"""Auto-generated Airflow DAG for scale-forecasting run {run_id}.

Generated by scale_forecasting.airflow_emit — do not edit by hand. To change the run, edit the
config and re-emit; the run_id (this file's identity) is a digest of that config.

Every task calls a callable in scale_forecasting.airflow_tasks against the staged config below, so
this DAG runs the identical building blocks as a local ``python -m scale_forecasting.main`` run.
"""

from __future__ import annotations

import pendulum
from airflow import DAG
from airflow.operators.python import PythonOperator

from scale_forecasting import airflow_tasks

# The staged config whose digest is this run's id; every task loads it and re-derives the run.
RUN_ID = {run_id_lit}
CONFIG_URI = {config_uri_lit}

with DAG(
    dag_id={dag_id_lit},
    description="scale-forecasting run {run_id}",
    schedule=None,
    start_date=pendulum.datetime(2024, 1, 1, tz="UTC"),
    catchup=False,
    tags=["scale-forecasting"],
) as dag:
'''


def _op(
    var: str,
    task_id: str,
    callable_name: str,
    *,
    family: str | None = None,
    trigger_rule: str | None = None,
) -> str:
    """Render one ``PythonOperator`` block bound to an `airflow_tasks` callable (indented for the
    DAG context)."""
    lines = [
        f"    {var} = PythonOperator(",
        f"        task_id={_str(task_id)},",
        f"        python_callable=airflow_tasks.{callable_name},",
    ]
    op_kwargs = '{"config_uri": CONFIG_URI'
    if family is not None:
        op_kwargs += f', "family": {_str(family)}'
    op_kwargs += "}"
    lines.append(f"        op_kwargs={op_kwargs},")
    if trigger_rule is not None:
        lines.append(f"        trigger_rule={_str(trigger_rule)},")
    lines.append("    )")
    return "\n".join(lines)


def _list(vars_: list[str]) -> str:
    """Render a task list as ``[a, b, c]`` (one element stays ``a`` so edges read naturally)."""
    return vars_[0] if len(vars_) == 1 else "[" + ", ".join(vars_) + "]"


def _shared_families(cfg: RunConfig, run_dag: RunDag) -> tuple[list[str], list[str]]:
    """The families that share an ephemeral Ray / Dataproc cluster (else empty), from the live
    predicates.

    Uses the exact `shared_clusters.shared_ray_inputs` / ``shared_spark_inputs`` rules `main.run`
    uses, so the
    emitted bracket matches what a live run would provision: ≥2 ephemeral Ray families (no standing
    cluster) share one Ray cluster; ≥2 ephemeral ``spark_mode="cluster"`` families share Dataproc
    clusters. Serverless Spark and single-family cases return empty (each runs standalone).

    Returns *families*, not clusters, and that is why the DAG shape is unaffected by how many
    Dataproc clusters the run turns out to need. A mixed CPU/GPU run gets one cluster per hardware
    kind, but they are created and deleted by the same single task pair — so the bracket emitted
    here is "all cluster families, bracketed", whether that is one cluster behind it or two.
    """
    from .shared_clusters import shared_ray_inputs, shared_spark_inputs

    python_jobs = run_dag.python_jobs
    ray_families: list[str] = []
    if cfg.compute.ray_cluster_name is None and shared_ray_inputs(python_jobs) is not None:
        ray_families = [j.family for j in python_jobs if j.runtime == "ray"]
    spark_families: list[str] = []
    if shared_spark_inputs(python_jobs) is not None:
        spark_families = [
            j.family
            for j in python_jobs
            if j.runtime == "spark"
            and j.compute is not None
            and j.compute.spark_mode == "cluster"
            and j.compute.spark_cluster_name is None
        ]
    return ray_families, spark_families


def emit_airflow_dag(cfg: RunConfig, config_uri: str, *, dag_id: str | None = None) -> str:
    """Render a run's execution DAG as an Airflow ``dag_<run_id>.py`` source string (pure, offline).

    Resolves the config into its DAG (`dag.plan_dag`) and emits a standalone file: ``begin_run``,
    one ``PythonOperator`` per family on its resolved runtime, the ensemble node (``barrier``
    downstream of the families or ``microbatch`` in parallel), ``finalize_run`` as the terminal
    join, and — when the run has several ephemeral Ray/Dataproc-cluster families — the
    shared-cluster create/delete bracket. ``config_uri`` is the ``gs://`` (or local) URI the tasks
    load the config from; it is embedded verbatim as the file's ``CONFIG_URI``. ``dag_id`` defaults
    to ``scale_forecasting_<run_id>``. Touches no GCP — the output is deterministic and
    parse/compile-checkable offline.
    """
    from .dag import plan_dag

    run_dag = plan_dag(cfg)
    run_id = run_dag.run_id
    dag_id = dag_id or f"scale_forecasting_{run_id}"

    families = run_dag.families  # DAG order: statistical, ml, deep_learning, native
    ray_families, spark_families = _shared_families(cfg, run_dag)
    clustered = set(ray_families) | set(spark_families)
    direct = [f for f in families if f not in clustered]  # families gated straight off begin_run

    ensemble_enabled = run_dag.ensemble_enabled
    microbatch = cfg.compute.ensemble.mode == "microbatch"

    out: list[str] = [
        _PREAMBLE.format(
            run_id=run_id,
            run_id_lit=_str(run_id),
            config_uri_lit=_str(config_uri),
            dag_id_lit=_str(dag_id),
        )
    ]

    # --- tasks -----------------------------------------------------------------
    out.append("    # --- open the run: header RUNNING -------------------------------------")
    out.append(_op("begin_run", "begin_run", "begin_run"))

    out.append("\n    # --- one job per model family, on its resolved runtime ----------------")
    for family in families:
        if family == "native":
            out.append(_op("native", "native", "run_native"))
        else:
            out.append(_op(family, family, "run_family", family=family))

    if ray_families:
        out.append("\n    # --- shared ephemeral Ray cluster (>=2 Ray families) -----------------")
        out.append(_op("create_ray_cluster", "create_ray_cluster", "create_ray_cluster"))
        out.append(
            _op(
                "delete_ray_cluster",
                "delete_ray_cluster",
                "delete_ray_cluster",
                trigger_rule="all_done",
            )
        )
    if spark_families:
        out.append("\n    # --- shared ephemeral Dataproc cluster (>=2 cluster families) --------")
        out.append(_op("create_spark_cluster", "create_spark_cluster", "create_spark_cluster"))
        out.append(
            _op(
                "delete_spark_cluster",
                "delete_spark_cluster",
                "delete_spark_cluster",
                trigger_rule="all_done",
            )
        )

    if ensemble_enabled:
        mode = "microbatch (parallel)" if microbatch else "barrier (post-join)"
        out.append(f"\n    # --- ensemble node: {mode} ---")
        out.append(_op("ensemble", "ensemble", "run_ensemble"))

    out.append("\n    # --- close the run: combined header status ---------------------------")
    out.append(_op("finalize_run", "finalize_run", "finalize_run", trigger_rule="all_done"))

    # --- edges -----------------------------------------------------------------
    out.append("\n    # --- dependencies ----------------------------------------------------")
    if direct:
        out.append(f"    begin_run >> {_list(direct)}")
    if ray_families:
        out.append(
            f"    begin_run >> create_ray_cluster >> {_list(ray_families)} >> delete_ray_cluster"
        )
    if spark_families:
        out.append(
            f"    begin_run >> create_spark_cluster >> {_list(spark_families)} "
            ">> delete_spark_cluster"
        )

    delete_tasks = (["delete_ray_cluster"] if ray_families else []) + (
        ["delete_spark_cluster"] if spark_families else []
    )

    if ensemble_enabled and not microbatch:
        # Barrier: the ensemble runs after every family, then finalize.
        out.append(f"    {_list(families)} >> ensemble")
        leaves = ["ensemble", *delete_tasks]
    elif ensemble_enabled and microbatch:
        # Microbatch: the ensemble runs in parallel with the families, gated only on begin_run.
        out.append("    begin_run >> ensemble")
        leaves = ["ensemble", *direct, *delete_tasks]
    else:
        leaves = [*direct, *delete_tasks]

    out.append(f"    {_list(leaves)} >> finalize_run")

    return "\n".join(out) + "\n"
