CREATE OR REPLACE MODEL `proj.scale_forecasting.sf_model_arima_plus_bq_test_f8487395b49d`
OPTIONS(
  model_type = 'ARIMA_PLUS',
  time_series_id_col = 'ts_id',
  time_series_timestamp_col = 'ds',
  time_series_data_col = 'y',
  horizon = 28,
  data_frequency = 'DAILY'
)
AS (
  training_data AS (
    SELECT ts_id, ds, y
  FROM `proj.scale_forecasting.source_series_native`
  WHERE ts_id IN (SELECT ts_id FROM `proj.scale_forecasting.source_series_native` GROUP BY ts_id ORDER BY ts_id LIMIT 100)
  ),
  custom_holiday AS (
  SELECT * FROM UNNEST([
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2015-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2015-01-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2015-02-16' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2015-05-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day__observed' AS holiday_name, DATE '2015-07-03' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2015-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2015-09-07' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2015-10-12' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2015-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2015-11-26' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2015-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2016-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2016-01-18' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2016-02-15' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2016-05-30' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2016-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2016-09-05' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2016-10-10' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2016-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2016-11-24' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2016-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day__observed' AS holiday_name, DATE '2016-12-26' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2017-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day__observed' AS holiday_name, DATE '2017-01-02' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2017-01-16' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2017-02-20' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2017-05-29' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2017-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2017-09-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2017-10-09' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day__observed' AS holiday_name, DATE '2017-11-10' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2017-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2017-11-23' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2017-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2018-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2018-01-15' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2018-02-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2018-05-28' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2018-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2018-09-03' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2018-10-08' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2018-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day__observed' AS holiday_name, DATE '2018-11-12' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2018-11-22' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2018-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2019-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2019-01-21' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2019-02-18' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2019-05-27' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2019-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2019-09-02' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2019-10-14' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2019-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2019-11-28' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2019-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2020-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2020-01-20' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2020-02-17' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2020-05-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day__observed' AS holiday_name, DATE '2020-07-03' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2020-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2020-09-07' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2020-10-12' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2020-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2020-11-26' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2020-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2021-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2021-01-18' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2021-02-15' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2021-05-31' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day__observed' AS holiday_name, DATE '2021-06-18' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day' AS holiday_name, DATE '2021-06-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2021-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day__observed' AS holiday_name, DATE '2021-07-05' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2021-09-06' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2021-10-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2021-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2021-11-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day__observed' AS holiday_name, DATE '2021-12-24' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2021-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day__observed' AS holiday_name, DATE '2021-12-31' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2022-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2022-01-17' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2022-02-21' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2022-05-30' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day' AS holiday_name, DATE '2022-06-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day__observed' AS holiday_name, DATE '2022-06-20' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2022-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2022-09-05' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2022-10-10' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2022-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2022-11-24' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2022-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day__observed' AS holiday_name, DATE '2022-12-26' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2023-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day__observed' AS holiday_name, DATE '2023-01-02' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2023-01-16' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2023-02-20' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2023-05-29' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day' AS holiday_name, DATE '2023-06-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2023-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2023-09-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2023-10-09' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day__observed' AS holiday_name, DATE '2023-11-10' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2023-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2023-11-23' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2023-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2024-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2024-01-15' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2024-02-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2024-05-27' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day' AS holiday_name, DATE '2024-06-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2024-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2024-09-02' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2024-10-14' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2024-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2024-11-28' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2024-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2025-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2025-01-20' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2025-02-17' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2025-05-26' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day' AS holiday_name, DATE '2025-06-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2025-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2025-09-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2025-10-13' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2025-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2025-11-27' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2025-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2026-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2026-01-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2026-02-16' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2026-05-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day' AS holiday_name, DATE '2026-06-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day__observed' AS holiday_name, DATE '2026-07-03' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2026-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2026-09-07' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2026-10-12' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2026-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2026-11-26' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2026-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2027-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2027-01-18' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2027-02-15' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2027-05-31' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day__observed' AS holiday_name, DATE '2027-06-18' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day' AS holiday_name, DATE '2027-06-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2027-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day__observed' AS holiday_name, DATE '2027-07-05' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2027-09-06' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2027-10-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2027-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2027-11-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day__observed' AS holiday_name, DATE '2027-12-24' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2027-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day__observed' AS holiday_name, DATE '2027-12-31' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2028-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2028-01-17' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2028-02-21' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2028-05-29' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day' AS holiday_name, DATE '2028-06-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2028-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2028-09-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2028-10-09' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day__observed' AS holiday_name, DATE '2028-11-10' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2028-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2028-11-23' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2028-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2029-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2029-01-15' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2029-02-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2029-05-28' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day' AS holiday_name, DATE '2029-06-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2029-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2029-09-03' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2029-10-08' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2029-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day__observed' AS holiday_name, DATE '2029-11-12' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2029-11-22' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2029-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2030-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2030-01-21' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2030-02-18' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2030-05-27' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day' AS holiday_name, DATE '2030-06-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2030-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2030-09-02' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2030-10-14' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2030-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2030-11-28' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2030-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2031-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2031-01-20' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2031-02-17' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2031-05-26' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day' AS holiday_name, DATE '2031-06-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2031-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2031-09-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2031-10-13' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2031-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2031-11-27' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2031-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2032-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2032-01-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2032-02-16' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2032-05-31' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day__observed' AS holiday_name, DATE '2032-06-18' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day' AS holiday_name, DATE '2032-06-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2032-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day__observed' AS holiday_name, DATE '2032-07-05' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2032-09-06' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2032-10-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2032-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2032-11-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day__observed' AS holiday_name, DATE '2032-12-24' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2032-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day__observed' AS holiday_name, DATE '2032-12-31' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2033-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2033-01-17' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2033-02-21' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2033-05-30' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day' AS holiday_name, DATE '2033-06-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day__observed' AS holiday_name, DATE '2033-06-20' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2033-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2033-09-05' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2033-10-10' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2033-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2033-11-24' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2033-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day__observed' AS holiday_name, DATE '2033-12-26' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2034-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day__observed' AS holiday_name, DATE '2034-01-02' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2034-01-16' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2034-02-20' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2034-05-29' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day' AS holiday_name, DATE '2034-06-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2034-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2034-09-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2034-10-09' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day__observed' AS holiday_name, DATE '2034-11-10' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2034-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2034-11-23' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2034-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'New_Year_s_Day' AS holiday_name, DATE '2035-01-01' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Martin_Luther_King_Jr__Day' AS holiday_name, DATE '2035-01-15' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Washington_s_Birthday' AS holiday_name, DATE '2035-02-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Memorial_Day' AS holiday_name, DATE '2035-05-28' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Juneteenth_National_Independence_Day' AS holiday_name, DATE '2035-06-19' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Independence_Day' AS holiday_name, DATE '2035-07-04' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Labor_Day' AS holiday_name, DATE '2035-09-03' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Columbus_Day' AS holiday_name, DATE '2035-10-08' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day' AS holiday_name, DATE '2035-11-11' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Veterans_Day__observed' AS holiday_name, DATE '2035-11-12' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Thanksgiving_Day' AS holiday_name, DATE '2035-11-22' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days),
    STRUCT('US' AS region, 'Christmas_Day' AS holiday_name, DATE '2035-12-25' AS primary_date, 1 AS preholiday_days, 1 AS postholiday_days)
  ])
)
);

INSERT INTO `proj.scale_forecasting.forecast_predictions`
  (run_id, ts_id, model_type, compute_engine, forecast_date, yhat, yhat_lower, yhat_upper, quantiles)
SELECT
  @run_id, ts_id, 'arima_plus', 'bigquery',
  DATE(forecast_timestamp), forecast_value,
  prediction_interval_lower_bound, prediction_interval_upper_bound, NULL
FROM ML.FORECAST(MODEL `proj.scale_forecasting.sf_model_arima_plus_bq_test_f8487395b49d`, STRUCT(28 AS horizon, 0.8 AS confidence_level));

-- ===== next model =====

INSERT INTO `proj.scale_forecasting.forecast_predictions`
  (run_id, ts_id, model_type, compute_engine, forecast_date, yhat, yhat_lower, yhat_upper, quantiles)
SELECT
  @run_id, ts_id, 'timesfm', 'bigquery',
  DATE(forecast_timestamp), forecast_value,
  prediction_interval_lower_bound, prediction_interval_upper_bound, NULL
FROM AI.FORECAST(
    (SELECT ts_id, ds, y FROM `proj.scale_forecasting.source_series_native` WHERE ts_id IN (SELECT ts_id FROM `proj.scale_forecasting.source_series_native` GROUP BY ts_id ORDER BY ts_id LIMIT 100)),
    data_col => 'y',
    timestamp_col => 'ds',
    id_cols => ['ts_id'],
    horizon => 28,
    confidence_level => 0.8);